language: bash
dist: bionic
sudo: required
env:
  global:
    - DOCKER_REPO=alpine-mariadb
    - TAG="${TRAVIS_TAG:-latest}"
branches:
  only:
    - master

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
script:
  - docker version
  - docker login -u "$DOCKER_USERID" -p "$DOCKER_PASSWORD"
  - docker buildx create --use
  - echo $TAG
  - docker buildx build --platform=linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/ppc64le --tag $DOCKER_USERID/$DOCKER_REPO:$TAG --push .
