language: bash
dist: bionic
env:
  global:
    - DOCKER_REPO=alpine-mariadb
    - TAG="${TRAVIS_TAG:-latest}"
branches:
  only:
    - master

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - mkdir -p ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
script:
  - docker version
  - docker login -u "$DOCKER_USERID" -p "$DOCKER_PASSWORD"
  - docker buildx create --use
  - docker buildx build --platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/ppc64le --tag
    $DOCKER_USERID/$DOCKER_REPO:$TAG --push .
